
services:
  kickny-bot:
    build: .
    container_name: kickny-bot
    restart: unless-stopped
    ports:
      - "${API_HOST}:${API_PORT}:${API_PORT}"
    volumes:
      - ./.env:/app/.env
    environment:
      - API_HOST=${API_HOST:-127.0.0.1}
      - API_PORT=${API_PORT:-8000}
      - TZ=Europe/Moscow